module.exports = [
 { name: "Node 1" },
 { name: "Node 2" },
 { name: "Node 3" },
 { name: "Node 4" },
 { name: "Node 5" },
 { name: "Node 6" },
 { name: "Node 7" },
 { name: "Node 8" },
 { name: "Node 9" },
 { name: "Node 10" },
 { name: "Node 11" },
 { name: "Node 13" },
 { name: "Node 14" },
 { name: "Node 15" },
 { name: "Node 16" },
 { name: "Node 17" },
 { name: "Node 18" },
 { name: "Node 19" },
 { name: "Node 20" },
];